### ISSUE TITLE
Why i am getting icons view like this?

### ISSUE THREAD

**Issue by raviteja06** [code-mc/material-icon-lib#17] opened 2015-10-24 15:12 UTC
![screenshot_2015-10-24-20-34-27 1](https://cloud.githubusercontent.com/assets/3385730/10711115/88f1ec8e-7a8f-11e5-8642-2e5713570233.png)

How can i fix it? It was fine until today morning.

**Comment by code-mc** [comment] 2015-10-24 15:14
In situations like this providing the actual code you used that led up to this could be useful.

**Comment by raviteja06** [comment] 2015-10-25 01:53
here is the code 

    <net.steamcrafted.materialiconlib.MaterialIconView
                        android:layout_width="@dimen/_30sdp"
                        android:layout_height="@dimen/_30sdp"
                        android:layout_gravity="center"
                        android:padding="@dimen/_2sdp"
                        android:visibility="visible"
                        app:materialIcon="facebook_box"
                        app:materialIconColor="@color/white" />


and epp extension 

    xmlns:app="http://schemas.android.com/apk/res-auto"

FYI. Its looks normal in android studio. But only shows outline in  phone

**Comment by raviteja06** [comment] 2015-10-30 07:31
@code-mc any status on this issue? I re download the library, invalidated the cache. No Luck. 

FYI, i created new project and imported the library and tried it on same phone and pc. It worked there.

**Comment by code-mc** [comment] 2015-10-30 17:18
I'm not trying to be rude here but doesn't that pretty much confirm the problem is not on the libraries end?

**Comment by raviteja06** [comment] 2015-10-30 17:21
Bud, I don't have problem in giving one more shot. But if it happens again in new project, will you look into fixing this?

**Comment by PureDark** [comment] 2015-11-06 09:29
I kinda ran into the same problem...
well the drawable built from MaterialDrawableBuilder sometimes worked great but sometimes appear to be only showing the outline 
I guess there might be some compatibility issue

**Comment by code-mc** [comment] 2015-11-19 14:47
Thanks @PureDark , if that unfortunately isn't the problem I suppose we'll have to continue our search...

**Comment by etemplar** [comment] 2015-11-27 13:27
Yep, it's pretty strange issue out there.
Left image part is showing app running on the android 4.2.2.
Right image part is showing the same app running on the android 5.1.0.

![issue](https://cloud.githubusercontent.com/assets/9402154/11442093/66782e9e-9523-11e5-9b46-9f898fc9c7a4.PNG)

**Comment by code-mc** [comment] 2015-11-27 17:47
Hey @etemplar which views are you using the icon in? The one provided by the library or some custom one?

**Comment by etemplar** [comment] 2015-11-28 13:08
I am generating Drawable via MaterialDrawableBuilder and applying it to CircleImageView (https://github.com/hdodenhof/CircleImageView) programmatically by setImageDrawable method.

**Comment by etemplar** [comment] 2015-11-28 14:27
Built-in ImageView shows generated Drawable as it should.

**Comment by udiboy1209** [comment] 2015-12-03 20:38
Faced the same issue when trying to build a BitmapDescriptor for a custom Google Maps marker icon.
I guess MaterialDrawableBuilder has some issue.

Did some digging, Why does this [line](https://github.com/code-mc/material-icon-lib/blob/master/materialiconlib/src/main/java/net/steamcrafted/materialiconlib/MaterialDrawableBuilder.java#L56) 
    
    paint.setStyle(Paint.Style.STROKE);

not use `Style.FILL` or `Style.FILL_AND_STROKE` ?

**Comment by code-mc** [comment] 2015-12-03 23:02
@udiboy1209 That could very well be the reason for the weird behavior! Can't believe I didn't notice this... I'm checking this out asap!

**Comment by udiboy1209** [comment] 2015-12-03 23:13
I did check it. That seems to be the problem for me. Worked as expected when I used `Paint.Style.FILL_AND_STROKE`

Should I open a PR for this basic change? 

And btw, I'm using a locally compiled library now but would prefer you release it to mavenCentral or a similar server

**Comment by code-mc** [comment] 2015-12-04 18:53
@udiboy1209 I'm pushing a new version of the library in an hour or so with the fix applied :)

**Comment by code-mc** [comment] 2015-12-04 19:07
I've tested using the suggested circle icon view and the new (1.0.7) version renders the icons properly inside that view, also tried with the old version and it indeed renders wrong in that one.

So I'm going to assume it is fixed now although I haven't tested a proper sample.

Closing for now, feel free to open a new issue if the bug re-appears!

**Closed by code-mc** 2015-12-04 19:07 UTC

**Comment by shwalabaka** [comment] 2016-05-26 16:29
Had the same situation with android:hardwareAccelerated="false" in my manifest file.
